export const ADD_CARD = 'ADD_CARD';
export const SET_CARD_DUE_DATE = 'SET_CARD_DUE_DATE';
export const ADD_CARD_SUBTASK = 'ADD_CARD_SUBTASK';
export const REMOVE_CARD_SUBTASK = 'REMOVE_CARD_SUBTASK';
export const CHANGE_CARD_DESCRIPTION = 'CHANGE_CARD_DESCRIPTION';
export const SET_CARD_COLOR = 'SET_CARD_COLOR';
export const DELETE_CARD = 'DELETE_CARD';
export const MOVE_CARD = 'MOVE_CARD';
export const LOAD_CARDS_BY_ID = 'LOAD_CARDS_BY_ID';
export const UPDATE_CARDS_BY_ID = 'UPDATE_CARDS_BY_ID';

