export const LOAD_PROJECTS_BY_ID = 'LOAD_PROJECTS_BY_ID';
export const LOAD_PROJECT = 'LOAD_PROJECT';
export const UPDATE_PROJECT = 'UPDATE_PROJECT';
export const REORDER_LISTS = 'REORDER_LISTS';
export const UPDATE_PROJECT_TAGS = 'UPDATE_PROJECT_TAGS';
export const ADD_TAG = 'ADD_TAG';
export const ADD_PROJECT = 'ADD_PROJECT';
export const REMOVE_PROJECT = 'REMOVE_PROJECT';
export const CHANGE_LOADED_STATE = 'CHANGE_LOADED_STATE';
export const SET_PROJECT_LOADED_STATE = 'SET_PROJECT_LOADED_STATE';
export const SET_TEMP_PROJECT_SETTINGS = 'SET_TEMP_PROJECT_SETTINGS';

