export const LOAD_PROJECTS_BY_ID = 'LOAD_PROJECTS_BY_ID';
export const UPDATE_PROJECT = 'UPDATE_PROJECT';
export const REORDER_LISTS = 'REORDER_LISTS';
export const UPDATE_LIST_IDS = 'UPDATE_LIST_IDS';
export const UPDATE_PROJECT_TAGS = 'UPDATE_PROJECT_TAGS';
export const ADD_TAG = 'ADD_TAG';
