export const LOAD_SUBTASKS_BY_ID = 'LOAD_SUBTASKS_BY_ID';
export const FETCH_SUBTASKS_BY_ID = 'FETCH_SUBTASKS_BY_ID';
export const UPDATE_SUBTASKS_BY_ID = 'UPDATE_SUBTASKS_BY_ID';
export const ADD_SUBTASK = 'ADD_SUBTASK';
export const UPDATE_SUBTASK = 'UPDATE_SUBTASK';
export const REMOVE_SUBTASK = 'REMOVE_SUBTASK';
