export const LOAD_COMMENTS_BY_ID = 'LOAD_COMMENTS_BY_ID';
export const FETCH_COMMENTS_BY_ID = 'FETCH_COMMENTS_BY_ID';
export const ADD_COMMENT = 'ADD_COMMENT';
export const UPDATE_COMMENT = 'UPDATE_COMMENT';
export const REMOVE_COMMENT = 'REMOVE_COMMENT';
