export const LOAD_BOARDS_BY_ID = 'LOAD_BOARDS_BY_ID';
export const UPDATE_BOARD = 'UPDATE_BOARD';
export const REORDER_LISTS = 'REORDER_LISTS';
export const UPDATE_LIST_IDS = 'UPDATE_LIST_IDS';
export const UPDATE_BOARD_TAGS = 'UPDATE_BOARD_TAGS';
export const ADD_TAG = 'ADD_TAG';
