export const LOAD_TASKS_DUE_SOON = 'LOAD_TASKS_DUE_SOON';
export const ADD_TASK_DUE_SOON = 'ADD_TASK_DUE_SOON';
export const DELETE_TASK_DUE_SOON = 'DELETE_TASK_DUE_SOON';
export const UPDATE_TASK_DUE_SOON = 'UPDATE_TASK_DUE_SOON';
